name: setup-helm-azure-tpl
description: Setup Helm azure-tpl plugin


inputs:
  version:
    description: Plugin version
    type: string

runs:
  using: "composite"
  steps:
    - name: "Install Helm azure-tpl plugin"
      shell: bash
      run: |
        #!/bin/bash
        set -e
        
        if [[ -z "$AZURE_TPL_VERSION" || "$AZURE_TPL_VERSION" == "latest" ]]; then
                AZURE_TPL_GIT_VERSION="main"
                AZURE_TPL_OCI_VERSION="latest"
        fi
        
        echo "getting version of Helm"
        HELM_VERSION_TEXT=$(helm version --template='{{.Version}}')
        echo "got Helm version \"${HELM_VERSION_TEXT}\""
        
        HELM_VERSION=""
        if [[ "$HELM_VERSION_TEXT" == "v3."* ]]; then
                echo "detected Helm v3"
                HELM_VERSION=3
        elif [[ "$HELM_VERSION_TEXT" == "v4."* ]]; then
                echo "detected Helm v4"
                HELM_VERSION=4
        else
                echo "invalid Helm version found: ${HELM_VERSION_TEXT}"
                exit 1
        fi

        # add helm env vars
        eval $(helm env)

        echo "helm plugin dir: ${HELM_PLUGINS}"
        
        case "$HELM_VERSION" in
                3)
                        echo "uninstall plugin"
                        helm plugin uninstall azure-tpl || true
        
                        echo "install plugin via git (version: $AZURE_TPL_GIT_VERSION)"
                        helm plugin install https://github.com/webdevops/helm-azure-tpl.git --version="$AZURE_TPL_GIT_VERSION"
                        ;;
        
                4)
                        echo "uninstall plugin"
                        helm plugin uninstall azure-tpl || true
        
                        echo "install plugin via oci (version: $AZURE_TPL_OCI_VERSION)"
                        helm plugin install "oci://ghcr.io/webdevops/helm-azure-tpl/azure-tpl-cli:${AZURE_TPL_OCI_VERSION}" --verify=false
                        helm plugin install "oci://ghcr.io/webdevops/helm-azure-tpl/azure-tpl-getter:${AZURE_TPL_OCI_VERSION}" --verify=false
                        ;;
        
                *)
                        echo "invalid Helm version found, only version 3 or 4 are supported: ${HELM_VERSION_TEXT}"
                        exit 1
        esac
        echo "succeeded"
        exit 0
      env:
        AZURE_TPL_VERSION: ${{ inputs.version }}
        HOSTEDTOOLCACHE: ${{ runner.tool_cache }}
